CREATE SEQUENCE GRU.GRU_REJECT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE GRU.GRU_REJECT_TAB
(
    ID               NUMBER(12),
    SYSTEMACCOUNT    VARCHAR2(32 BYTE),
    VISTA_TAB_ID        NUMBER(12),
    UTERRARIO        NUMBER(9),
    OLDTBAL          NUMBER(20,3),
    NEWTBAL          NUMBER(20,3),
    FRONT_TIMESTAMP  DATE,
    FRONT_STATUS     VARCHAR2(3 BYTE),
    REJECT_DESC      VARCHAR2(256 BYTE),
    CHECK_STATUS     VARCHAR2(3 BYTE),
    CHECK_DESC       VARCHAR2(256 BYTE),
    CHECK_USER       VARCHAR2(20 BYTE),
    CHECK_TIMESTAMP  DATE,
    SVFE_LOAD_ID     VARCHAR2(256 BYTE)
);

CREATE USER ACC_APP_ADAPTER IDENTIFIED BY "root";
ALTER USER ACC_APP_ADAPTER DEFAULT TABLESPACE USERS;
ALTER USER ACC_APP_ADAPTER QUOTA UNLIMITED ON USERS;

CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_TRANS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS
(
    ID         NUMBER,
    TRANS_ID   NUMBER(18),
    MSG_TYPE   VARCHAR2(64 BYTE),
    DIR        VARCHAR2(16 BYTE),
    MSG        CLOB,
    INS_TS     DATE                               DEFAULT sysdate,
    NODE_ID    VARCHAR2(8 BYTE)
);

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS
(
    ID          NUMBER,
    SYSTEM_ID   VARCHAR2(256 BYTE),
    REQUEST_ID  VARCHAR2(256 BYTE),
    EVENT_TYPE  VARCHAR2(256 BYTE),
    DATA        CLOB,
    STATUS      VARCHAR2(256 BYTE),
    RESP_CODE   VARCHAR2(16 BYTE),
    RESP_DESC   VARCHAR2(256 BYTE),
    INS_TS      DATE                              DEFAULT sysdate,
    UPD_TS      DATE                              DEFAULT sysdate
);

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG
(
    ID               NUMBER(12),
    SYSTEMID         VARCHAR2(255 BYTE),
    EVENT_TYPE       VARCHAR2(255 BYTE),
    ENTITY_TYPE      VARCHAR2(255 BYTE),
    TOPIC_IN         VARCHAR2(255 BYTE),
    STATUS_IN        NUMBER(1),
    TOPIC_OUT        VARCHAR2(255 BYTE),
    STATUS_OUT       NUMBER(1),
    INS_TS           DATE,
    UPD_TS           DATE
);
