--liquibase formatted sql

--changeset illya:adapter-004-trans
CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS
(
    ID         NUMBER,
    SYSTEM_ID  VARCHAR2(256 BYTE),
    REQUEST_ID VARCHAR2(256 BYTE),
    EVENT_TYPE VARCHAR2(256 BYTE),
    DATA       CLOB,
    STATUS     VARCHAR2(256 BYTE),
    RESP_CODE  VARCHAR2(16 BYTE),
    RESP_DESC  VARCHAR2(256 BYTE),
    INS_TS     DATE DEFAULT SYSDATE,
    UPD_TS     DATE DEFAULT SYSDATE
);

--rollback DROP TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS;


--changeset illya:adapter-005-io-msgs
CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS
(
    ID       NUMBER,
    TRANS_ID NUMBER(18),
    MSG_TYPE VARCHAR2(64 BYTE),
    DIR      VARCHAR2(16 BYTE),
    MSG      CLOB,
    INS_TS   DATE DEFAULT SYSDATE,
    NODE_ID  VARCHAR2(8 BYTE)
);

--rollback DROP TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS;


--changeset illya:adapter-006-config
CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG
(
    ID          NUMBER(12),
    SYSTEMID    VARCHAR2(255 BYTE),
    EVENT_TYPE  VARCHAR2(255 BYTE),
    ENTITY_TYPE VARCHAR2(255 BYTE),
    TOPIC_IN    VARCHAR2(255 BYTE),
    STATUS_IN   NUMBER(1),
    TOPIC_OUT   VARCHAR2(255 BYTE),
    STATUS_OUT  NUMBER(1),
    INS_TS      DATE,
    UPD_TS      DATE
);

--rollback DROP TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG;