--liquibase formatted sql

--changeset illya:adapter-007-trans-pk
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS
    ADD CONSTRAINT PK_APP_ADAPTER_TRANS
        PRIMARY KEY (ID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS DROP CONSTRAINT PK_APP_ADAPTER_TRANS;


--changeset illya:adapter-008-io-pk
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS
    ADD CONSTRAINT PK_APP_ADAPTER_IO_MSGS
        PRIMARY KEY (ID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS DROP CONSTRAINT PK_APP_ADAPTER_IO_MSGS;


--changeset illya:adapter-009-config-pk
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG
    ADD CONSTRAINT PK_APP_ADAPTER_CONFIG
        PRIMARY KEY (ID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG DROP CONSTRAINT PK_APP_ADAPTER_CONFIG;


--changeset illya:adapter-010-request-id-unique
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS
    ADD CONSTRAINT UK_APP_ADAPTER_TRANS_REQUEST
        UNIQUE (REQUEST_ID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS DROP CONSTRAINT UK_APP_ADAPTER_TRANS_REQUEST;


--changeset illya:adapter-011-system-id-unique
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG
    ADD CONSTRAINT UK_APP_ADAPTER_CONFIG_SYSTEM
        UNIQUE (SYSTEMID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG DROP CONSTRAINT UK_APP_ADAPTER_CONFIG_SYSTEM;


--changeset illya:adapter-012-io-trans-fk
ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS
    ADD CONSTRAINT FK_APP_ADAPTER_IO_TRANS
        FOREIGN KEY (TRANS_ID)
        REFERENCES ACC_APP_ADAPTER.APP_ADAPTER_TRANS(ID);

--rollback ALTER TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS DROP CONSTRAINT FK_APP_ADAPTER_IO_TRANS;


--changeset illya:adapter-013-trans-status-index
CREATE INDEX ACC_APP_ADAPTER.IDX_APP_TRANS_STATUS
    ON ACC_APP_ADAPTER.APP_ADAPTER_TRANS (STATUS);

--rollback DROP INDEX ACC_APP_ADAPTER.IDX_APP_TRANS_STATUS;


--changeset illya:adapter-014-io-trans-index
CREATE INDEX ACC_APP_ADAPTER.IDX_APP_IO_TRANS_ID
    ON ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS (TRANS_ID);

--rollback DROP INDEX ACC_APP_ADAPTER.IDX_APP_IO_TRANS_ID;